### ISSUE TITLE
fails desk top set-up  cannot resolve (installed) xdg-utils

### ISSUE THREAD

**Issue by aplatypus** [flathub/com.jetbrains.IntelliJ-IDEA-Community#12]
Once installed the current/latest `com.jetbrains.IntelliJ-IDEA-Community` version's start-up wizard offers to create a desktop icon for the IDE.  This fails because it reports that it cannot use `xdg-utils` on my Ubuntu 18.10 system.

However `xdg-utils` are installed, as shown:

     $ sudo apt install    xdg-utils
     [sudo] password: 
     Reading package lists... Done
     Building dependency tree       
     Reading state information... Done
     xdg-utils is already the newest version (1.1.3-1ubuntu2).
     0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade

Evidently something is missing in the `flatpak` to provide or resolve this dependency.

**Comment by x80486** [comment]
The icon is already provided as part of the Flatpak installation, I don't think we would need another one.

I guess the trick here is to modify the "wizard" for the **IntelliJ IDEA**'s intro to not execute that step when running as Flatpak because the precondition of having the icon is already satisfied.

I can try to put an issue in their **YouTrack** (or you can do it if you want to), but my guess is that it won't get any traction since they currently don't support this release format.

By the way, I don't think the Flatpak can use your installed `xdg-utils` :wink:

**Comment by aplatypus** [comment]
As may be ... however the star-up wizard/install fails as shown

    xdg-utils not installed

That's a whole bummer since the `snap` model fails if the `/home/...` is on a different partition or uses a `symlink`.  

Is there an "appimage"?

**Comment by Globegitter** [comment]
@aplatypus I ran into the same issue but simply unselected the option and all is now working as expected without any error message.

**Comment by mmrezaie** [comment]
As of today it still cannot see the xdg-utils of the system. I'm on ubuntu 19.04.

**Comment by aplatypus** [comment]
@Globegitter  ... I am not clear which option you were refering to?  I have Ubuntu 19.0 these days.

**Comment by b-hayes** [comment]
Wanted to try PopOS. Would be nice to just install phpstorm and get working but I cant get past this error.

**Comment by JosephGonzalez03** [comment]
Hello, I'm using Pop OS 20 and ran into the same issue. Uncheck the option on the first setup page to add intellij the search menu and everything should be fine. :^)

**Comment by jonathanmdr** [comment]
> Hello, I'm using Pop OS 20 and ran into the same issue. Uncheck the option on the first setup page to add intellij the search menu and everything should be fine. :^)

Thank's! :)
