### ISSUE TITLE
Can't install Scala SDK within Flatpak

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.jetbrains.IntelliJ-IDEA-Community#23]
I discovered that it's currently impossible to install Scala SDKs when you're running in Flatpak... 
```
Cannot run program "java" (in directory "/home/kevin/.var/app/com.jetbrains.IntelliJ-IDEA-Community/cache/tmp/sbt-project"): error=2, No such file or directory
```
But, you can select already installed Scala SDKs. Glass half full I would say.

**Comment by x80486** [comment]
Peek into issue number 13, in `com.jetbrains.IntelliJ-IDEA-Ultimate` and let me know if that workaround works for you. You can always use `SDKMAN` or `asdf`, and these kind of issues will go away.

Bundling the Scala SDK (or any other SDK for that matter) doesn't make much sense (even though that's the Flatpak mantra) since everyone uses a different version, so there will be a population that will be left behind anyways.

**Comment by KevinAtSesam** [comment]
Hey, sorry for not getting back sooner. 

It's indeed the same issue, and I switched to using SdkMan to download and manage my own versions of all Java tools. Little hurdle to get over initially, but now a lot easier to manage.

**Comment by x80486** [comment]
Hi @KevinAtSesam, I'm going to close this one for the time being. Let me know if you were expecting a different resolution or anything else for that matter. Feel free to reopen this one if so.

**Comment by Eonfge** [comment]
Ow, totally fine. I forgot about it and I've been using SDK Man ever since.
