### ISSUE TITLE
Consider Allowing ARM64 Users

### ISSUE THREAD

**Issue by CuriousTommy** [flathub/com.jetbrains.IntelliJ-IDEA-Community#29]
Hello,

I noticed that you have [a restriction](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/blob/master/flathub.json#L2) to only allow `x86_64` users. Would it be possible to also allow `aarch64` users as well?

**Comment by x80486** [comment]
It is not possible to port installations the way this is "being built" as a Flatpak package. We would have to recompile again the (very few) binaries that this is shipping using the architecture in question.

Your [best](https://youtrack.jetbrains.com/issue/JBR-383) [bet](https://youtrack.jetbrains.com/issue/JBR-2074) would be to ask JetBrains to port the software to the architecture you are using.

Let me know if you have any other question(s), otherwise, feel free to close the issue.

**Comment by CuriousTommy** [comment]
> Your best bet would be to ask JetBrains to port the software to the architecture you are using.

So I download Intellij IDEA on my Pinebook Pro (Manjaro ARM) and kotlin/java seems to work fine. Unless I am overlooking something, I don't think JetBrains need to fix anything.

The only issue I currently experience is [the lack of a file watcher](https://confluence.jetbrains.com/display/IDEADEV/Compiling+File+Watcher). But that sounds like it can be fixable (provide a built version that users can manually apply in their settings).

> It is not possible to port installations the way this is "being built" as a Flatpak package. We would have to recompile again the (very few) binaries that this is shipping using the architecture in question.

With that being said, I understand if the flatpak side of things is not designed to be cross-platform.

**Comment by TingPing** [comment]
> With that being said, I understand if the flatpak side of things is not designed to be cross-platform.

Flatpak in no way cares what architecture it is ran on and Flathub supports aarch64. Lets not jump to nonsensical conclusions.

**Comment by x80486** [comment]
> So I download Intellij IDEA on my Pinebook Pro (Manjaro ARM) and kotlin/java seems to work fine. Unless I am overlooking something, I don't think JetBrains need to fix anything.

You were able to do that because you have a JRE for ARM and you are using that one instead of the bundled one. They don't support that architecture out-of-the-box, but you can still get the release and use your own JRE – I think that might even work in the Flatpak by defining an `IDEA_JDK` environment variable pointing to your JDK...but like I said, there will be a few binaries that are not going to work, and also some plugins.

**Comment by x80486** [comment]
I don't have any device to test this, but are you able to use any of the Linux versions [here](https://www.jetbrains.com/idea/download/other.html) **without any modifications** in your ARM device?

**Comment by cobalt2727** [comment]
Got the community edition to launch just fine on my Pi 4
