### ISSUE TITLE
Runtime set to freedesktop sdk instead of platform

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.jetbrains.IntelliJ-IDEA-Community#8]
Is there a reason why that is ?

```json
"runtime": "org.freedesktop.Sdk"
```

I would have expected:

```json
"runtime": "org.freedesktop.Platform"
```

**Comment by x80486** [comment]
I don't know much about it, but the reason for this one –and I guess for all other IDEs- it's because users can install, manually, any of the available Sdk extensions and those would be accessible (and usable) under `/usr/lib/sdk/...`, without specifying anything in the manifest – pretty handy and cool, I would say.

**Comment by bilelmoussaoui** [comment]
It also allows you to have utilities that are available only in the SDK and hence in the build time, but could be useful for an IDE such as git for example.

**Comment by x80486** [comment]
@ghisvail, I'm going to close this one, if you need more information feel free to reopen it.
