### ISSUE TITLE
Notifications after completion of tests

### ISSUE THREAD

**Issue by t1u1** [flathub/com.jetbrains.IntelliJ-IDEA-Community#90]
When I run tests, I don't get notifications of the test being completed in the flatpak version. The native version does (atleast Android Studio does, so I assume IntelliJ also does have this feature).

When using FlatSeal, I see that the checkbox for Notification permission is disabled (greyed out). That is, I am not able to enable / disable the Notification permission.

Could this be a flatpak packaging issue?

**Comment by x80486** [comment]
Hi @t1u1. What test runner are you using?

I use both versions: Flatpak and "native", but I mostly run Java/Erlang stuff, and all the notifications are within IntelliJ, they never show up in the operating system.

**Comment by x80486** [comment]
Turns out I turn off most of the notifications from almost all applications :grin:

I see what you meant, but `--talk-name=org.freedesktop.Notifications` will do the trick. It's working for me on a VM that I have with Ubuntu.

What operating system are you using? Also, make sure you have the notifications for the application in question turned on — just in case :wink:
