### ISSUE TITLE
Tighten permissions

### ISSUE THREAD

**Issue by dave-kennedy** [flathub/com.jetbrains.IntelliJ-IDEA-Community#98]
Similar to #66, I think it would be nice to have some explanation about the permissions.

Specifically I'm wondering about the need for `host` access. It was removed in #45 but it appears that never made it into the master branch.

I'm also wondering about `device=all`. Seems a bit excessive.

This seems to work fine for my purposes:

```
[Context]
sockets=!ssh-auth
devices=!all
filesystems=!host;!xdg-run/app/com.discordapp.Discord;!xdg-run/gnupg;!xdg-run/keyring;home/.aws;home/.gradle;home/.java;home/.m2;home/.sdkman;home/src
```

**Comment by x80486** [comment]
It's nearly impossible to know how anyone is going to use anything. The permissions are set for almost all use cases:

- `filesystems=host` because you can have anything installed in your system and would like to be able to use it as before
- `device=all` because there are plugins that use the camera, people develop for certain controllers, etc.
- `sockets=ssh-auth` because (ideally) most developers use `git` using the `Secure Shell Protocol`

**Comment by dave-kennedy** [comment]
Makes sense. Worth a mention in the readme at least.

I ran into some weird issue and had to completely reinstall anyways, so probably won't mess with the permissions again.

**Comment by dave-kennedy** [comment]
Also see #101.
